name: lint

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  golangcli-lint:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Initialize Go modules
        run: go mod tidy
      - uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          go_version: "1.22"
          reporter: github-pr-review
          level: warning
          golangci_lint_flags: "--config=.golangci.yml"
          fail_level: true
